--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.45.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 14/9/2019 18:47:47
-- Server version: 8.0.15
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS naranjarepublik;

CREATE DATABASE naranjarepublik
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Set default database
--
USE naranjarepublik;

--
-- Create table `users`
--
CREATE TABLE users (
  UserId int(11) NOT NULL AUTO_INCREMENT,
  FullName varchar(200) NOT NULL,
  CompanyName varchar(200) NOT NULL,
  IsAdmin tinyint(1) DEFAULT 0,
  RoleId int(11) NOT NULL DEFAULT 0,
  Username varchar(255) NOT NULL,
  Email varchar(255) NOT NULL,
  Password varchar(255) DEFAULT NULL,
  Image text DEFAULT NULL,
  Birthday date DEFAULT NULL,
  Status enum ('Activo', 'Inactivo') NOT NULL DEFAULT 'Activo',
  DisableLogin tinyint(1) NOT NULL DEFAULT 0,
  Note mediumtext DEFAULT NULL,
  Address text DEFAULT NULL,
  AlternativeAddress text DEFAULT NULL,
  Phone varchar(20) DEFAULT NULL,
  AlternativePhone varchar(20) DEFAULT NULL,
  GenderId int(11) NOT NULL,
  StickyNote mediumtext DEFAULT NULL,
  EnableWebNotification tinyint(1) NOT NULL DEFAULT 1,
  EnableEmailNotification tinyint(1) NOT NULL DEFAULT 1,
  City varchar(50) DEFAULT NULL,
  Country varchar(255) DEFAULT NULL,
  CreatedAt datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  Deleted int(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (UserId)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_unicode_ci;

--
-- Create index `Deleted` on table `users`
--
ALTER TABLE users
ADD INDEX Deleted (Deleted);

--
-- Create index `Email` on table `users`
--
ALTER TABLE users
ADD INDEX Email (Email);

--
-- Create table `occupation`
--
CREATE TABLE occupation (
  OccupationId int(11) NOT NULL AUTO_INCREMENT,
  LocalDescription varchar(100) DEFAULT NULL,
  GlobalDescription varchar(100) DEFAULT NULL,
  IsActive int(1) DEFAULT NULL,
  Deleted int(1) DEFAULT NULL,
  PRIMARY KEY (OccupationId)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci,
COMMENT = 'Ocupaciones de los Suscriptores';

--
-- Create table `industrywork`
--
CREATE TABLE industrywork (
  IndustryWorkId int(11) NOT NULL AUTO_INCREMENT,
  LocalDescription varchar(100) DEFAULT NULL,
  GlobalDescription varchar(100) DEFAULT NULL,
  IsActive int(1) DEFAULT NULL,
  Deleted int(1) DEFAULT NULL,
  PRIMARY KEY (IndustryWorkId)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci,
COMMENT = 'Industria donde estan trabajando los que se encuentran registrados en la Economia naranja.';

-- 
-- Dumping data for table users
--
-- Table naranjarepublik.users does not contain any data (it is empty)

-- 
-- Dumping data for table occupation
--
INSERT INTO occupation VALUES
(1, 'Académico', 'Academic', 1, 0),
(2, 'Actor', 'Actor', 1, 0),
(3, 'Locutor', 'Announcer', 1, 0),
(4, 'Arquitecto', 'Architect', 1, 0),
(5, 'Representante artístico', 'Artistic Representative', 1, 0),
(6, 'Administrador de negocios', 'Business administrator', 1, 0),
(7, 'Compositor', 'Composer', 1, 0),
(8, 'Creativo/Publicista', 'Creative/Publicist', 1, 0),
(9, 'Gestor cultural', 'Cultural Manager', 1, 0),
(10, 'Economista', 'Economist', 1, 0),
(11, 'Diseñador de modas', 'Fashion designer', 1, 0),
(12, 'Director de cine / TV', 'Film / TV Director', 1, 0),
(13, 'Productor de cine / TV', 'Film / TV producer', 1, 0),
(14, 'Cineasta', 'Filmmaker', 1, 0),
(15, 'Diseñador gráfico', 'Graphic designer', 1, 0),
(16, 'Periodista', 'Journalists', 1, 0),
(17, 'Abogado', 'Lawyer', 1, 0),
(18, 'Music producer', 'Productor musical', 1, 0),
(19, 'Músico', 'Musician', 1, 0),
(20, 'Pintor', 'Painter', 1, 0),
(21, 'Fotógrafo', 'Photographer', 1, 0),
(22, 'Publicista', 'Publicist', 1, 0),
(23, 'Modelo de pasarela', 'Runway model', 1, 0),
(24, 'Guionista', 'Screenwriter', 1, 0),
(25, 'Escultor', 'Sculptor', 1, 0),
(26, 'Cantante', 'Singer', 1, 0),
(27, 'Desarrollador de software', 'Software developer', 1, 0),
(28, 'Estudiante', 'Student', 1, 0),
(29, 'Urbanista', 'Urbanist', 1, 0),
(30, 'Desarrollador de videojuegos', 'Videogame developer', 1, 0),
(31, 'Writer', 'Escritor', 1, 0),
(32, 'Otros', 'Others', NULL, NULL);

-- 
-- Dumping data for table industrywork
--
INSERT INTO industrywork VALUES
(1, 'Arquitectura', 'Architecture', 1, 0),
(2, 'Publicidad', 'Advertising', 1, 0),
(3, 'Conciertos', 'Concerts', 1, 0),
(4, 'Artesanía', 'Crafts', 1, 0),
(5, 'Cultural', 'Cultural', 1, 0),
(6, 'Danza', 'Dance', 1, 0),
(7, 'Editorial (Libros, Diarios, Revistas)', 'Editorial (Books, Newspapers, Magazines)', 1, 0),
(8, 'Educación', 'Education', 1, 0),
(9, 'Moda', 'Fashion', 1, 0),
(10, 'Gastronomía', 'Gastronomy', 1, 0),
(11, 'Diseño gráfico e ilustración', 'Graphic Design and Illustration', 1, 0),
(12, 'Diseño industrial', 'Industrial design', 1, 0),
(13, 'Propiedad intelectual', 'Intellectual property', 1, 0),
(14, 'Diseño de interiores', 'Interior design', 1, 0),
(15, 'Joyería', 'Jewelry', 1, 0),
(16, 'Literatura', 'Literature', 1, 0),
(17, 'Cine', 'Movie theater', 1, 0),
(18, 'Música', 'Music', 1, 0),
(19, 'Orquestas / Ópera ', 'Orchestras / Opera ', 1, 0),
(20, 'Pintura', 'Painting', 1, 0),
(21, 'Fotógrafia', 'Photography', 1, 0),
(22, 'Radio', 'Radio', 1, 0),
(23, 'Escultura', 'Sculpture', 1, 0),
(24, 'Software', 'Software', 1, 0),
(25, 'Teatro', 'Theater', 1, 0),
(26, 'Turismo y patrimonio cultural', 'Tourism and Cultural Heritage', 1, 0),
(27, 'TV', 'TV', 1, 0),
(28, 'Video', 'Video', 1, 0),
(29, 'Video Juegos', 'Video game', 1, 0),
(30, 'Otros', 'Others', 1, 0);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;